var hazardLookup = [
       {value:"bushfire1", alias:"Bushfire (Emergency)"},
       {value:"bushfire2", alias:"Bushfire (Emergency - homes lost)"},
       {value:"bushfire3", alias:"Bushfire (Emergency - homes & lives lost)"},
       {value:"cyclone1", alias:"Cyclone (Category 1)"},
       {value:"cyclone2", alias:"Cyclone (Category 2)"},
       {value:"cyclone3", alias:"Cyclone (Category 3)"},
       {value:"cyclone4", alias:"Cyclone (Category 4)"},
       {value:"cyclone5", alias:"Cyclone (Category 5)"},
       {value:"cyclone", alias:"Cyclone (all)"},
       {value:"drought", alias:"Drought"},
       {value:"earthquake2", alias:"Earthquake (2.0 MMI)"},
       {value:"earthquake3", alias:"Earthquake (3.0 MMI)"},
       {value:"earthquake4", alias:"Earthquake (4.0 MMI)"},
       {value:"earthquake5", alias:"Earthquake (5.0 MMI)"},
       {value:"earthquake6", alias:"Earthquake (6.0 MMI)"},
       {value:"earthquake7", alias:"Earthquake (7.0 MMI)"},
       {value:"flooding2", alias:"Flooding (Moderate)"},
       {value:"flooding3", alias:"Flooding (Major)"},
       {value:"hail0", alias:"Hail (0-3 cm)"},
       {value:"hail1", alias:"Hail (3-5 cm)"},
       {value:"hail2", alias:"Hail (6-8 cm)"},
       {value:"hail3", alias:"Hail (9cm and above)"},
       {value:"rain", alias:"Rain"},
       {value:"severewinds1", alias:"Severe Winds (90-120kph)"},
       {value:"severewinds2", alias:"Severe Winds (120kph+)"},
       {value:"stormsurge0", alias:"Storm Surge (0-1m)"},
       {value:"stormsurge1", alias:"Storm Surge (1-2m)"},
       {value:"stormsurge2", alias:"Storm Surge (2-3m)"},
       {value:"stormsurge3", alias:"Storm Surge (3-4m)"},
       {value:"stormsurge4", alias:"Storm Surge (4-6m)"},
       {value:"tornado0", alias:"Tornado (F0)"},
       {value:"tornado1", alias:"Tornado (F1)"},
       {value:"tornado2", alias:"Tornado (F2)"},
       {value:"tornado3", alias:"Tornado (F3)"},
       {value:"tornado4", alias:"Tornado (F4)"},
       {value:"windgusts1", alias:"Wind Gusts (90-120kph)"},
       {value:"windgusts2", alias:"Wind Gusts (120kph+)"}
]
